" Name: t1-faker
" Description: T1 x Faker inspired dark colorscheme (black base + SK red accent)
" Author: generated by ChatGPT
" License: MIT

if exists('g:colors_name')
  finish
endif

set background=dark
hi clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 't1-faker'

" Core palette
let s:bg0     = '#0B0B0D'   " jersey black
let s:bg1     = '#111115'
let s:bg2     = '#1A1A20'
let s:fg0     = '#EDEDED'   " clean white text
let s:fg1     = '#C8C8C8'
let s:fg2     = '#8A8A92'

let s:red0    = '#EA002C'   " SK Red (accent)
let s:red1    = '#B80020'   " deeper crimson (mouse shell shade)
let s:red2    = '#FF3B4D'   " bright highlight (kill-confirm ping)

let s:gold0   = '#C8A951'   " trophy accent
let s:orange0 = '#F47725'   " SK Orange (rare highlight)
let s:green0  = '#2BD67B'
let s:blue0   = '#4FA3FF'
let s:purple0 = '#B18CFF'

let s:none = 'NONE'

function! s:HI(group, fg, bg, attr, sp) abort
  execute 'hi' a:group
        \ 'guifg=' . (a:fg  ==# '' ? s:none : a:fg)
        \ 'guibg=' . (a:bg  ==# '' ? s:none : a:bg)
        \ 'gui='   . (a:attr==# '' ? s:none : a:attr)
        \ 'guisp=' . (a:sp  ==# '' ? s:none : a:sp)
endfunction

" Editor UI
call s:HI('Normal',        s:fg0,   s:bg0,   'NONE',      '')
call s:HI('NormalFloat',   s:fg0,   s:bg2,   'NONE',      '')
call s:HI('FloatBorder',   s:red0,  s:bg2,   'NONE',      '')

call s:HI('CursorLine',    '',      s:bg1,   'NONE',      '')
call s:HI('CursorColumn',  '',      s:bg1,   'NONE',      '')
call s:HI('ColorColumn',   '',      s:bg1,   'NONE',      '')

call s:HI('LineNr',        s:fg2,   s:bg0,   'NONE',      '')
call s:HI('CursorLineNr',  s:red2,  s:bg1,   'BOLD',      '')
call s:HI('SignColumn',    s:fg2,   s:bg0,   'NONE',      '')

call s:HI('VertSplit',     s:bg2,   s:bg0,   'NONE',      '')
call s:HI('WinSeparator',  s:bg2,   s:bg0,   'NONE',      '')

call s:HI('StatusLine',    s:fg0,   s:bg2,   'NONE',      '')
call s:HI('StatusLineNC',  s:fg2,   s:bg1,   'NONE',      '')
call s:HI('TabLine',       s:fg2,   s:bg1,   'NONE',      '')
call s:HI('TabLineSel',    s:fg0,   s:bg2,   'BOLD',      '')
call s:HI('TabLineFill',   s:fg2,   s:bg0,   'NONE',      '')

call s:HI('Visual',        '',      '#2A0010','NONE',     '')
call s:HI('Search',        s:bg0,   s:gold0, 'NONE',      '')
call s:HI('IncSearch',     s:bg0,   s:red2,  'BOLD',      '')
call s:HI('MatchParen',    s:fg0,   '#2A1A1A','BOLD',     '')

call s:HI('Pmenu',         s:fg1,   s:bg2,   'NONE',      '')
call s:HI('PmenuSel',      s:fg0,   '#22222A','BOLD',     '')
call s:HI('PmenuSbar',     '',      '#1C1C22','NONE',     '')
call s:HI('PmenuThumb',    '',      '#2E2E38','NONE',     '')

call s:HI('Folded',        s:fg2,   s:bg1,   'NONE',      '')
call s:HI('FoldColumn',    s:fg2,   s:bg0,   'NONE',      '')

call s:HI('Directory',     s:blue0, s:bg0,   'BOLD',      '')
call s:HI('Title',         s:fg0,   s:bg0,   'BOLD',      '')
call s:HI('NonText',       '#3A3A44',s:bg0,  'NONE',      '')
call s:HI('Whitespace',    '#2F2F38',s:bg0,  'NONE',      '')

call s:HI('ErrorMsg',      s:red2,  s:bg0,   'BOLD',      '')
call s:HI('WarningMsg',    s:orange0,s:bg0,  'BOLD',      '')
call s:HI('MoreMsg',       s:green0,s:bg0,   'BOLD',      '')
call s:HI('Question',      s:green0,s:bg0,   'BOLD',      '')

" Syntax
call s:HI('Comment',       s:fg2,   s:bg0,   'ITALIC',    '')
call s:HI('Constant',      s:purple0,s:bg0,  'NONE',      '')
call s:HI('String',        s:green0,s:bg0,   'NONE',      '')
call s:HI('Character',     s:green0,s:bg0,   'NONE',      '')
call s:HI('Number',        s:purple0,s:bg0,  'NONE',      '')
call s:HI('Boolean',       s:purple0,s:bg0,  'NONE',      '')
call s:HI('Float',         s:purple0,s:bg0,  'NONE',      '')

call s:HI('Identifier',    s:fg0,   s:bg0,   'NONE',      '')
call s:HI('Function',      s:fg0,   s:bg0,   'BOLD',      '')

call s:HI('Statement',     s:red2,  s:bg0,   'NONE',      '')
call s:HI('Conditional',   s:red2,  s:bg0,   'NONE',      '')
call s:HI('Repeat',        s:red2,  s:bg0,   'NONE',      '')
call s:HI('Operator',      s:fg1,   s:bg0,   'NONE',      '')
call s:HI('Keyword',       s:red2,  s:bg0,   'NONE',      '')
call s:HI('Exception',     s:red2,  s:bg0,   'NONE',      '')

call s:HI('PreProc',       s:orange0,s:bg0,  'NONE',      '')
call s:HI('Include',       s:orange0,s:bg0,  'NONE',      '')
call s:HI('Define',        s:orange0,s:bg0,  'NONE',      '')
call s:HI('Macro',         s:orange0,s:bg0,  'NONE',      '')

call s:HI('Type',          s:blue0, s:bg0,   'NONE',      '')
call s:HI('StorageClass',  s:blue0, s:bg0,   'NONE',      '')
call s:HI('Structure',     s:blue0, s:bg0,   'NONE',      '')
call s:HI('Typedef',       s:blue0, s:bg0,   'NONE',      '')

call s:HI('Special',       s:gold0, s:bg0,   'NONE',      '')
call s:HI('Delimiter',     s:fg1,   s:bg0,   'NONE',      '')
call s:HI('Underlined',    s:blue0, s:bg0,   'UNDERLINE', '')
call s:HI('Todo',          s:bg0,   s:gold0, 'BOLD',      '')

" Diff / VCS
call s:HI('DiffAdd',       '',      '#0E2A16','NONE',     '')
call s:HI('DiffChange',    '',      '#0E1E2A','NONE',     '')
call s:HI('DiffDelete',    '',      '#2A0E14','NONE',     '')
call s:HI('DiffText',      s:bg0,   s:blue0, 'BOLD',      '')

" LSP / Diagnostics (works in Vim + popular plugins, and in Neovim)
call s:HI('DiagnosticError', s:red2,   s:bg0, 'NONE', '')
call s:HI('DiagnosticWarn',  s:orange0,s:bg0, 'NONE', '')
call s:HI('DiagnosticInfo',  s:blue0,  s:bg0, 'NONE', '')
call s:HI('DiagnosticHint',  s:fg2,    s:bg0, 'NONE', '')

call s:HI('DiagnosticUnderlineError', '', '', 'UNDERCURL', s:red2)
call s:HI('DiagnosticUnderlineWarn',  '', '', 'UNDERCURL', s:orange0)
call s:HI('DiagnosticUnderlineInfo',  '', '', 'UNDERCURL', s:blue0)
call s:HI('DiagnosticUnderlineHint',  '', '', 'UNDERCURL', s:fg2)

" GitGutter (optional)
hi! link GitGutterAdd    DiffAdd
hi! link GitGutterChange DiffChange
hi! link GitGutterDelete DiffDelete

" Terminal palette (for :terminal, etc.)
let g:terminal_color_0  = s:bg0
let g:terminal_color_1  = s:red0
let g:terminal_color_2  = s:green0
let g:terminal_color_3  = s:gold0
let g:terminal_color_4  = s:blue0
let g:terminal_color_5  = s:purple0
let g:terminal_color_6  = '#44C2C2'
let g:terminal_color_7  = s:fg1
let g:terminal_color_8  = s:fg2
let g:terminal_color_9  = s:red2
let g:terminal_color_10 = '#4BFF9A'
let g:terminal_color_11 = '#FFD36E'
let g:terminal_color_12 = '#7BC0FF'
let g:terminal_color_13 = '#D1B4FF'
let g:terminal_color_14 = '#74F2F2'
let g:terminal_color_15 = s:fg0
